config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'authors#index', as: 'root'
  get '/authors', to: 'authors#index', as: 'authors_index'
  get '/authors/new', to: 'authors#new', as: 'authors_new'
  post '/authors/create', to: 'authors#create', as: 'authors_create'
  get '/authors/:id', to: 'authors#view', as: 'authors_view'
  get '/authors/:id/edit', to: 'authors#edit', as: 'authors_edit'
  
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :author
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_one :address, dependent: :destroy
  # has_one :address, class_name: "Address", foreign_key: "author_id"
  has_many :books, dependent: :destroy
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end
  
  def new
  end

  def create
    #p params
    author = Author.new
    author.name = params[:name]
    author.date_of_birth = params[:author][:date_of_birth]
    author.save

    redirect_to authors_index_path
  end

  def view
    @author = Author.find(params[:id])
  end

  def edit
    @author = Author.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/edit.html.erb
<h1>Edit Author Details</h1>

app/views/authors/index.html.erb
<h1>Authors</h1>

<ul>
<% @authors.each do |author| %>
  <li><%= author.name %></li>
<% end %>
</ul>

<%= link_to "Add an Author", authors_new_path %>

app/views/authors/new.html.erb
<h1>Add an Author</h1>

<%= form_tag("/authors/create", method: "post") do %>
  <p>
    <%= label_tag(:name, "Author's Name") %>
    <%= text_field_tag(:name) %>
    <br>
    <%= label_tag(:date_of_birth, "Date of Birth") %>
    <%= date_field(:author, :date_of_birth) %>
  </p>
  <p>
    <%= submit_tag("Add Author") %>
  </p>
<% end %>

app/views/authors/view.html.erb
<h1>Author Details</h1>

<h2>
  <%= @author.name %>
</h2>

<% if @author.date_of_birth %>
  <p>
    Born: <%= @author.date_of_birth %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AssociationsLesson</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>